# Generated by Erlang.mk. Edit at your own risk!

src/follow.erl:: src/twitter.erl; @touch $@
src/register.erl:: src/twitter.erl; @touch $@
src/retweet.erl:: src/twitter.erl; @touch $@
src/search.erl:: src/twitter.erl; @touch $@
src/signin.erl:: src/twitter.erl; @touch $@
src/tweet.erl:: src/twitter.erl; @touch $@

COMPILE_FIRST += twitter
